### ISSUE TITLE
UI worked on v2.2.4, but failed on v2.2.5.

### ISSUE THREAD

**Issue by Joevaen** [GitSquared/edex-ui#980]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.5`)
 - [v2.2.4 &v2.2.5 ] `vX.X.X` (specify other version)

**Running on:**
 - [ubuntu 18.04] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ yes] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

**_First_**: The UI v2.2.4 worked on my ubuntu 18.04 but v2.2.5 failed. Error looks like below:
`$ ./eDEX-UI-Linux-x86_64.AppImage 
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/qiao/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-UgOjGXB/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-UgOjGXB/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-UgOjGXB/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-UgOjGXB/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UgOjGXB/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-UgOjGXB/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-UgOjGXB/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-UgOjGXB/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-UgOjGXB/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:25612) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.uRlyaF)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UgOjGXB/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:25612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
**_Second_**: Although v2.2.4 works, an error pops up and keeps shown from startup :
![image](https://user-images.githubusercontent.com/46133615/102753152-a9101380-43a5-11eb-9c49-e974d86b6d89.png)

Whether I use clash or not, it always show "offline" and this error. Could you please tell me what to do in detail?

**Comment by wrac4242** [comment]
it looks like you dont have libc accessable, you may need to install lib C

and possibly try running of master branch

**Comment by GitSquared** [comment]
v2.2.5 just came out yesterday so no need to try out master.
The version of libc you're missing is GLIBC_2.28, you'll need to find out why & how to get it.

**Comment by cmbillman** [comment]
Everything fails after 10 seconds!!!

**Comment by lapsio** [comment]
I have similar error regarding GLIBC_2.28 on OpenSUSE 15.1

**Comment by GitSquared** [comment]
v2.2.6 releasing in a few mins with updated glibc
